title: GitHub Pages, Ubuntu, and Jekyll
description: Version 017 --- 20190702
show_downloads: true
google_analytics:

theme: jekyll-theme-hacker
# theme: jekyll-theme-midnight

# Fixing the "No GitHub API authentication could be found" ??
github: [metadata]


